from distutils.core import setup

setup(
    name='skool',
    version='0.1.0',
    author='Michal Vlasak',
    author_email='daeatel@gmail.com',
    packages=['skool'],
    scripts=[],
    url='https://github.com/daeatel/skool',
    license='LICENSE.txt',
    description='Online school package',
    long_description=open('README.txt').read(),
    install_requires=[
        "beautifulsoup4 == 4.3.2",
        "blinker == 1.3",
        "breadability == 0.1.20",
        "certifi == 14.5.14",
        "cffi == 0.9.2",
        "characteristic == 14.3.0",
        "chardet == 2.3.0",
        "cryptography == 0.8.1",
        "cssselect == 0.9.1",
        "Distance == 0.1.3",
        "Django == 1.7.5",
        "django-debug-toolbar == 1.3.0",
        "docopt == 0.6.2",
        "elasticsearch == 1.4.0",
        "enum34 == 1.0.4",
        "iso8601 == 0.1.10",
        "jusText == 2.1.1",
        "Lemmagen == 1.0.3",
        "lmdb == 0.84",
        "lxml == 3.4.2",
        "mongoengine == 0.8.7",
        "ndg-httpsclient == 0.3.3",
        "nltk == 3.0.2",
        "numpy == 1.9.2",
        "pyasn1 == 0.1.7",
        "pyasn1-modules == 0.0.5",
        "pycparser == 2.10",
        "pymongo == 2.8",
        "pyOpenSSL == 0.14",
        "pytz == 2015.2",
        "queuelib == 1.2.2",
        "requests == 2.6.0",
        "scikit-learn == 0.15.2",
        "scipy == 0.15.1",
        "Scrapy == 0.24.5",
        "service-identity == 14.0.0",
        "six == 1.9.0",
        "sqlparse == 0.1.14",
        "sumy == 0.3.0",
        "textblob == 0.9.0",
        "Twisted == 15.0.0",
        "urllib3 == 1.10.2",
        "w3lib == 1.11.0",
        "zope.interface == 4.1.2",
    ],
)
